// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SalonFlow.Infrastructure.Persistence;

#nullable disable

namespace SalonFlow.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(SalonFlowDbContext))]
    [Migration("20260916181338_AddSalonServices")]
    partial class AddSalonServices
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("SalonFlow.Domain.Appointments.Appointment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("TEXT");

                    b.Property<long>("Duration")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SalonId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ServiceId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("StaffMemberId")
                        .HasColumnType("TEXT");

                    b.Property<long>("StartsAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SalonId", "StartsAtUtc");

                    b.ToTable("Appointments", (string)null);
                });

            modelBuilder.Entity("SalonFlow.Domain.Services.SalonService", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("Duration")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SalonId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SalonId", "IsActive");

                    b.HasIndex("SalonId", "Name")
                        .IsUnique();

                    b.ToTable("SalonServices", (string)null);
                });

            modelBuilder.Entity("SalonFlow.Domain.StaffMembers.StaffMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SalonId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SalonId", "IsActive");

                    b.ToTable("StaffMembers", (string)null);
                });

            modelBuilder.Entity("SalonFlow.Infrastructure.Persistence.Appointments.AppointmentDetails", b =>
                {
                    b.Property<Guid>("AppointmentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("StaffMemberName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("AppointmentId");

                    b.ToTable("AppointmentDetails", (string)null);
                });

            modelBuilder.Entity("SalonFlow.Infrastructure.Persistence.Appointments.AppointmentDetails", b =>
                {
                    b.HasOne("SalonFlow.Domain.Appointments.Appointment", "Appointment")
                        .WithOne()
                        .HasForeignKey("SalonFlow.Infrastructure.Persistence.Appointments.AppointmentDetails", "AppointmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Appointment");
                });
#pragma warning restore 612, 618
        }
    }
}
